cargo-features = ["edition"]

[package]
name = "erlust"
edition = "2018"
version = "0.1.0"
authors = ["Léo Gaspard <leo@gaspard.io>"]
license = "MIT"
categories = ["asynchronous", "concurrency", "rust-patterns"]
keywords = ["actor", "erlang", "async", "serialization", "futures",
    "concurrency", "message-passing", "distributed-systems"]
description = "Erlang-like actor system for Rust"

[dependencies]
lazy_static = "1.1"
serde = "1.0"

[dependencies.futures-preview]
git = "https://github.com/rust-lang-nursery/futures-rs"
rev = "1b6e8150e7339478e73b87ff3d616010bdb1ab0b"

[dev-dependencies]
serde_derive = "1.0"
